### ISSUE TITLE
DEMO Required.

### ISSUE THREAD

**Issue by varunsridharan** [hemnathmouli/hnotify.js#1]
Hi,

Kindly create a demo page. and also improve README.MD File.

Provide some steps. on how to use this plugin in jquery

**Comment by hemnathmouli** [comment]
Thanks for remembering that.! Here is the demo page https://hemnathmouli.github.io/hnotify.js/

**Comment by varunsridharan** [comment]
@hemnathmouli soon i will be using in some of my project :)
